volumes:
  db-data:
  phpmyadmin-data:
services:
  backend:
    build: .
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - .:/app
    restart: always
    environment:
      - TZ=America/Bogota
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "${FORWARD_DB_PORT:-3306}"
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${FORWARD_PMA_PORT:-8080}:80
    environment:
      - PMA_ARBITRARY=1

