services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart:
      always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
